policy:
  - template: ["request.yml", "request_en.yml"]
    section:
      - id: ["logo-category"]
        block-list: []
        label:
          - name: "service"
            keys: ["service", "Service"]
          - name: "original"
            keys: ["original", "Original"]
          - name: "unknown"
            keys: ["None", "unknown"]
      - id: ["permission"]
        block-list: ["None", "No"]
        label:
          - name: "permitted"
            keys: ["Yes"]
